version: "3"
services:

  #purchase
  purchases_container:
    container_name: purchases_container
    ports:
      - "80:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: purchases_db
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: yes
      restart: always

  customer-service:
    # build: .
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_USER: micro_user
      MYSQL_PASSWORD: micro_password
      MYSQL_DB: micro_db
      #depends_on:
      restart: always
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=item_db
      - MYSQL_USER=item_user
      - MYSQL_PASSWORD=item_password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33063:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
